In [16]:
import pickle

# with open("../../../crypto-data/pickle_hour_cache/usdt_data_2025-09.pkl", "rb") as f:
#     obj = pickle.load(f)

In [2]:
from ohlc_figure_factor import OHLCFigureFactor

factor = OHLCFigureFactor('/home/craz/crypto/crypto-trading/figure_model/model_saved/baseline_epoch_52_train_0.02124_val_0.02302.pt', device='cuda', name='testohlc')

✅ Loaded OHLC CNN model from /home/craz/crypto/crypto-trading/figure_model/model_saved/baseline_epoch_52_train_0.02124_val_0.02302.pt
📱 Using device: cuda

In [4]:
import pandas as pd

factor_series = factor.calculate(obj, pd.Timestamp('2025-09-21 15:00:00'))

Processing symbols: 100%|██████████| 542/542 [00:32<00:00, 16.80it/s]

⚠️  Skipped 4 symbols with insufficient data (< 80h)

In [4]:
# pd.set_option('display.max_rows', None)
# len(factor_series)
factor_series

0GUSDT           -0.056230
1000000BOBUSDT    0.004523
1000000MOGUSDT   -0.003556
1000BONKUSDT     -0.030069
1000CATUSDT       0.000636
                    ...
ZKUSDT            0.000263
ZORAUSDT         -0.019671
ZRCUSDT           0.016174
ZROUSDT           0.000609
ZRXUSDT          -0.026831
Name: testohlc_factor, Length: 545, dtype: float32

In [5]:
with open("../backtest/factor_data/test/factor_2022-09.pkl", "rb") as f:
    obj = pickle.load(f)

In [11]:
with open("/home/craz/crypto/crypto-data/future_returns/future_returns_2025-01.pkl", "rb") as f:
    obj = pickle.load(f)

In [15]:
# pd.set_option('display.max_rows', None)

# obj.head()

,,return_1h,return_2h,return_3h,return_4h,return_5h,return_6h,return_7h,return_8h,return_10h,return_12h,...,return_42h,return_48h,return_54h,return_60h,return_72h,return_84h,return_96h,return_108h,return_120h,return_144h
open_time,symbol,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00,1000000MOGUSDT,0.005760,-0.021937,-0.030578,-0.032354,-0.032738,-0.019153,-0.031442,-0.031490,-0.023666,-0.029474,...,-0.015841,0.008833,0.027314,0.024146,0.145497,0.196573,0.194364,0.314276,0.369336,0.396553
2025-01-01 01:00:00,1000000MOGUSDT,-0.027539,-0.036130,-0.037896,-0.038278,-0.024771,-0.036989,-0.037037,-0.021812,-0.025439,-0.044578,...,-0.014700,0.018041,0.004821,0.003914,0.161321,0.180699,0.194206,0.323740,0.313478,0.344454
2025-01-01 02:00:00,1000000MOGUSDT,-0.008834,-0.010650,-0.011043,0.002847,-0.009718,-0.009767,0.005890,-0.001767,-0.007706,-0.014773,...,0.010699,0.052123,0.044417,0.046675,0.224883,0.210650,0.236810,0.329325,0.361620,0.382528
2025-01-01 03:00:00,1000000MOGUSDT,-0.001832,-0.002228,0.011785,-0.000891,-0.000941,0.014855,0.007130,0.011092,-0.008765,0.003516,...,0.044813,0.053181,0.073830,0.053479,0.227928,0.237187,0.271552,0.384055,0.368111,0.398217
2025-01-01 04:00:00,1000000MOGUSDT,-0.000397,0.013642,0.000943,0.000893,0.016718,0.008979,0.012948,0.002976,-0.004167,0.002084,...,0.027929,0.054172,0.062903,0.045094,0.263369,0.250521,0.262328,0.392797,0.392797,0.385703

In [17]:
with open("/home/craz/crypto/crypto-trading/strategy/backtest/factor_data/precious_ohlc_cnn/factor_2025-01.pkl", "rb") as f:
    obj = pickle.load(f)

In [22]:
pd.set_option('display.max_rows', None)

obj[:5000]

                                    factor_value
open_time           symbol
2025-01-01 00:00:00 1000000MOGUSDT     -0.021588
                    1000BONKUSDT        0.022658
                    1000CATUSDT         0.022428
                    1000CHEEMSUSDT      0.003550
                    1000FLOKIUSDT       0.045722
                    1000LUNCUSDT        0.029482
                    1000PEPEUSDT        0.038661
                    1000RATSUSDT        0.029811
                    1000SATSUSDT        0.027376
                    1000SHIBUSDT        0.020110
                    1000WHYUSDT         0.000581
                    1000XECUSDT        -0.002357
                    1000XUSDT           0.021302
                    1INCHUSDT           0.015656
                    1MBABYDOGEUSDT      0.028833
                    AAVEUSDT            0.006583
                    ACEUSDT             0.011697
                    ACHUSDT             0.004181
                    ACTUSDT             0.011987
                    ACXUSDT             0.025156
                    ADAUSDT             0.000989
                    AEROUSDT            0.008213
                    AEVOUSDT            0.015023
                    AGIXUSDT           -0.000074
                    AGLDUSDT           -0.022866
                    AIUSDT              0.009528
                    AIXBTUSDT           0.027863
                    AKTUSDT            -0.004024
                    ALGOUSDT            0.037156
                    ALICEUSDT           0.018201
                    ALPACAUSDT          0.009822
                    ALPHAUSDT           0.017589
                    ALTUSDT             0.016357
                    AMBUSDT             0.018716
                    ANKRUSDT            0.019956
                    APEUSDT             0.025766
                    API3USDT            0.008731
                    APTUSDT             0.002422
                    ARBUSDT             0.021242
                    ARKMUSDT           -0.007878
                    ARKUSDT             0.022010
                    ARPAUSDT            0.012511
                    ARUSDT              0.014472
                    ASTRUSDT            0.005120
                    ATAUSDT             0.005487
                    ATOMUSDT            0.016038
                    AUCTIONUSDT         0.012989
                    AVAUSDT            -0.004600
                    AVAXUSDT            0.022308
                    AXLUSDT             0.009090
                    AXSUSDT             0.045465
                    BADGERUSDT          0.017494
                    BAKEUSDT            0.001722
                    BALUSDT             0.002147
                    BANANAUSDT          0.032319
                    BANDUSDT            0.011390
                    BANUSDT             0.000234
                    BATUSDT             0.003976
                    BBUSDT              0.011465
                    BCHUSDT             0.013193
                    BEAMXUSDT           0.023184
                    BELUSDT             0.009648
                    BICOUSDT           -0.014823
                    BIGTIMEUSDT         0.013579
                    BLURUSDT            0.015091
                    BLZUSDT            -0.000074
                    BNBUSDT            -0.000932
                    BNTUSDT            -0.005551
                    BNXUSDT            -0.005689
                    BOMEUSDT            0.044422
                    BONDUSDT           -0.000074
                    BRETTUSDT           0.024003
                    BSVUSDT             0.022214
                    BSWUSDT            -0.004909
                    BTCDOMUSDT         -0.001260
                    BTCUSDT             0.034270
                    C98USDT             0.010009
                    CAKEUSDT            0.009068
                    CATIUSDT            0.003078
                    CELOUSDT            0.016024
                    CELRUSDT           -0.009493
                    CETUSUSDT          -0.010290
                    CFXUSDT             0.029403
                    CGPTUSDT            0.010607
                    CHESSUSDT           0.000572
                    CHILLGUYUSDT        0.041359
                    CHRUSDT             0.016786
                    CHZUSDT             0.007934
                    CKBUSDT             0.014445
                    COMBOUSDT          -0.013532
                    COMPUSDT           -0.012283
                    COSUSDT            -0.005906
                    COTIUSDT            0.000935
                    COWUSDT             0.019655
                    CRVUSDT            -0.004535
                    CTSIUSDT            0.008438
                    CYBERUSDT           0.013432
                    DARUSDT            -0.000074
                    DASHUSDT            0.011299
                    DEFIUSDT            0.017038
                    DEGENUSDT           0.026041
                    DEGOUSDT           -0.000341
                    DENTUSDT            0.049647
                    DEXEUSDT            0.003714
                    DGBUSDT            -0.000074
                    DIAUSDT             0.009045
                    DODOXUSDT           0.016435
                    DOGEUSDT            0.044101
                    DOGSUSDT            0.039540
                    DOTUSDT             0.000674
                    DRIFTUSDT          -0.010509
                    DUSKUSDT           -0.014935
                    DYDXUSDT            0.001198
                    DYMUSDT             0.018241
                    EDUUSDT             0.012376
                    EGLDUSDT           -0.006494
                    EIGENUSDT           0.012050
                    ENAUSDT             0.005632
                    ENJUSDT             0.015129
                    ENSUSDT             0.027824
                    ETCUSDT             0.035621
                    ETHFIUSDT           0.038944
                    ETHUSDT             0.031810
                    ETHWUSDT            0.015063
                    FARTCOINUSDT        0.072934
                    FETUSDT             0.015927
                    FIDAUSDT            0.003495
                    FILUSDT             0.023526
                    FIOUSDT             0.012930
                    FLMUSDT             0.016399
                    FLOWUSDT            0.014386
                    FLUXUSDT            0.012314
                    FTMUSDT             0.003719
                    FTTUSDT            -0.000074
                    FXSUSDT            -0.013545
                    GALAUSDT            0.024238
                    GASUSDT             0.007945
                    GHSTUSDT            0.012765
                    GLMRUSDT           -0.000074
                    GLMUSDT             0.007204
                    GMTUSDT            -0.022343
                    GMXUSDT            -0.000061
                    GOATUSDT            0.007686
                    GRASSUSDT           0.003041
                    GRTUSDT             0.006761
                    GTCUSDT             0.001961
                    GUSDT               0.013364
                    HBARUSDT            0.012471
                    HFTUSDT            -0.000627
                    HIFIUSDT           -0.001195
                    HIGHUSDT            0.012859
                    HIPPOUSDT           0.005162
                    HIVEUSDT           -0.014353
                    HMSTRUSDT           0.009517
                    HOOKUSDT            0.001278
                    HOTUSDT             0.005842
                    ICPUSDT             0.018195
                    ICXUSDT            -0.006574
                    IDEXUSDT           -0.000074
                    IDUSDT              0.020324
                    ILVUSDT             0.002888
                    IMXUSDT             0.025616
                    INJUSDT            -0.009586
                    IOSTUSDT            0.014881
                    IOTAUSDT            0.027076
                    IOTXUSDT            0.012442
                    IOUSDT              0.054284
                    JASMYUSDT          -0.005627
                    JOEUSDT            -0.000868
                    JTOUSDT             0.018757
                    JUPUSDT             0.033199
                    KAIAUSDT            0.050035
                    KASUSDT            -0.006355
                    KAVAUSDT           -0.006519
                    KDAUSDT             0.003717
                    KEYUSDT            -0.000074
                    KLAYUSDT           -0.000074
                    KMNOUSDT            0.015971
                    KNCUSDT             0.015080
                    KOMAUSDT           -0.003346
                    KSMUSDT             0.026213
                    LDOUSDT             0.010023
                    LEVERUSDT           0.005316
                    LINAUSDT           -0.001084
                    LINKUSDT           -0.007275
                    LISTAUSDT           0.001909
                    LITUSDT             0.000172
                    LOKAUSDT            0.018241
                    LOOMUSDT           -0.000074
                    LPTUSDT             0.023422
                    LQTYUSDT            0.017483
                    LRCUSDT             0.021078
                    LSKUSDT             0.031617
                    LTCUSDT             0.038137
                    LUMIAUSDT           0.007786
                    LUNA2USDT           0.017230
                    MAGICUSDT           0.010590
                    MANAUSDT            0.024078
                    MANTAUSDT           0.006095
                    MASKUSDT            0.009694
                    MAVUSDT            -0.000742
                    MBOXUSDT            0.022809
                    MDTUSDT            -0.000074
                    MEMEUSDT            0.014828
                    METISUSDT           0.003566
                    MEUSDT              0.000592
                    MEWUSDT             0.042518
                    MINAUSDT            0.008785
                    MKRUSDT             0.001179
                    MOCAUSDT           -0.007235
                    MOODENGUSDT         0.011137
                    MORPHOUSDT          0.057485
                    MOVEUSDT            0.000380
                    MOVRUSDT           -0.010522
                    MTLUSDT            -0.000516
                    MYROUSDT            0.012690
                    NEARUSDT            0.016801
                    NEIROETHUSDT        0.016672
                    NEIROUSDT           0.024495
                    NEOUSDT             0.007611
                    NFPUSDT             0.023052
                    NKNUSDT             0.009356
                    NMRUSDT             0.005246
                    NOTUSDT             0.026389
                    NTRNUSDT            0.008256
                    NULSUSDT            0.007016
                    OCEANUSDT          -0.000074
                    OGNUSDT            -0.003327
                    OMGUSDT             0.021319
                    OMNIUSDT            0.017330
                    OMUSDT              0.052855
                    ONDOUSDT           -0.016970
                    ONEUSDT             0.003011
                    ONGUSDT            -0.002256
                    ONTUSDT             0.032185
                    OPUSDT              0.008125
                    ORBSUSDT           -0.000074
                    ORCAUSDT            0.050665
                    ORDIUSDT            0.023575
                    OXTUSDT            -0.018404
                    PENDLEUSDT          0.018260
                    PENGUUSDT           0.019020
                    PEOPLEUSDT          0.065775
                    PERPUSDT            0.001266
                    PHBUSDT             0.017046
                    PIXELUSDT           0.007947
                    PNUTUSDT           -0.011802
                    POLUSDT             0.001412
                    POLYXUSDT           0.009522
                    PONKEUSDT           0.009877
                    POPCATUSDT          0.043316
                    PORTALUSDT          0.012115
                    POWRUSDT            0.003500
                    PYTHUSDT            0.000136
                    QNTUSDT             0.015283
                    QTUMUSDT            0.011601
                    QUICKUSDT          -0.001500
                    RADUSDT            -0.000074
                    RAREUSDT            0.000727
                    RAYSOLUSDT          0.013736
                    RAYUSDT            -0.000074
                    RDNTUSDT            0.004924
                    REEFUSDT            0.010765
                    REIUSDT             0.002710
                    RENDERUSDT          0.012106
                    RENUSDT            -0.000074
                    REZUSDT             0.020665
                    RIFUSDT             0.001900
                    RLCUSDT            -0.011486
                    RONINUSDT           0.007390
                    ROSEUSDT            0.011913
                    RPLUSDT             0.004363
                    RSRUSDT             0.003361
                    RUNEUSDT            0.022692
                    RVNUSDT             0.008754
                    SAFEUSDT            0.014036
                    SAGAUSDT            0.019445
                    SANDUSDT            0.040123
                    SANTOSUSDT          0.024096
                    SCRTUSDT           -0.012127
                    SCRUSDT            -0.003485
                    SCUSDT             -0.000074
                    SEIUSDT             0.007669
                    SFPUSDT             0.014125
                    SKLUSDT             0.005731
                    SLERFUSDT           0.005997
                    SNTUSDT            -0.000074
                    SNXUSDT             0.010673
                    SOLUSDT             0.031442
                    SPELLUSDT           0.008031
                    SPXUSDT             0.022871
                    SSVUSDT             0.005493
                    STEEMUSDT          -0.018078
                    STGUSDT             0.022238
                    STMXUSDT           -0.002607
                    STORJUSDT          -0.007029
                    STPTUSDT           -0.000074
                    STRAXUSDT          -0.000074
                    STRKUSDT            0.032199
                    STXUSDT             0.010244
                    SUIUSDT            -0.004880
                    SUNUSDT            -0.000688
                    SUPERUSDT           0.002242
                    SUSHIUSDT           0.005210
                    SWELLUSDT           0.057628
                    SXPUSDT            -0.001974
                    SYNUSDT            -0.009688
                    SYSUSDT             0.017712
                    TAOUSDT             0.005379
                    THETAUSDT           0.006896
                    THEUSDT             0.002475
                    TIAUSDT            -0.012470
                    TLMUSDT             0.013659
                    TNSRUSDT           -0.004374
                    TOKENUSDT          -0.001530
                    TONUSDT            -0.007879
                    TRBUSDT             0.026503
                    TROYUSDT            0.025101
                    TRUUSDT            -0.000669
                    TRXUSDT             0.033647
                    TURBOUSDT           0.017861
                    TUSDT               0.022878
                    TWTUSDT             0.001122
                    UMAUSDT             0.000114
                    UNFIUSDT           -0.000074
                    UNIUSDT             0.017887
                    USDCUSDT            0.003389
                    USTCUSDT            0.007486
                    USUALUSDT           0.010387
                    UXLINKUSDT         -0.002934
                    VANAUSDT            0.012526
                    VANRYUSDT           0.018277
                    VELODROMEUSDT      -0.004525
                    VETUSDT             0.010839
                    VIDTUSDT            0.008213
                    VIRTUALUSDT         0.039053
                    VOXELUSDT          -0.004449
                    WAVESUSDT          -0.000074
                    WAXPUSDT            0.014178
                    WIFUSDT             0.051735
                    WLDUSDT            -0.003452
                    WOOUSDT             0.028012
                    WUSDT               0.031564
                    XAIUSDT             0.012031
                    XEMUSDT            -0.000074
                    XLMUSDT             0.012745
                    XMRUSDT             0.014230
                    XRPUSDT             0.007533
                    XTZUSDT             0.010142
                    XVGUSDT            -0.004811
                    XVSUSDT            -0.001077
                    YFIUSDT             0.014229
                    YGGUSDT             0.008226
                    ZECUSDT            -0.000885
                    ZENUSDT             0.006604
                    ZETAUSDT            0.015588
                    ZILUSDT             0.027182
                    ZKUSDT              0.010144
                    ZROUSDT             0.021344
                    ZRXUSDT             0.007703
2025-01-01 01:00:00 1000000MOGUSDT     -0.031274
                    1000BONKUSDT        0.018123
                    1000CATUSDT         0.027175
                    1000CHEEMSUSDT     -0.003110
                    1000FLOKIUSDT       0.013956
                    1000LUNCUSDT        0.005687
                    1000PEPEUSDT        0.014351
                    1000RATSUSDT        0.029976
                    1000SATSUSDT        0.027465
                    1000SHIBUSDT        0.013250
                    1000WHYUSDT        -0.014411
                    1000XECUSDT         0.005379
                    1000XUSDT           0.016548
                    1INCHUSDT           0.008476
                    1MBABYDOGEUSDT      0.030100
                    AAVEUSDT            0.022323
                    ACEUSDT            -0.004220
                    ACHUSDT             0.003916
                    ACTUSDT             0.034325
                    ACXUSDT             0.024456
                    ADAUSDT             0.015123
                    AEROUSDT           -0.015590
                    AEVOUSDT            0.015114
                    AGIXUSDT           -0.000074
                    AGLDUSDT           -0.004525
                    AIUSDT             -0.005833
                    AIXBTUSDT           0.002258
                    AKTUSDT            -0.002370
                    ALGOUSDT            0.022015
                    ALICEUSDT           0.001000
                    ALPACAUSDT         -0.001457
                    ALPHAUSDT           0.016596
                    ALTUSDT             0.005221
                    AMBUSDT             0.020518
                    ANKRUSDT            0.017221
                    APEUSDT             0.016063
                    API3USDT            0.026585
                    APTUSDT            -0.011593
                    ARBUSDT             0.006160
                    ARKMUSDT            0.004346
                    ARKUSDT            -0.000292
                    ARPAUSDT            0.000445
                    ARUSDT              0.017467
                    ASTRUSDT            0.001926
                    ATAUSDT            -0.001603
                    ATOMUSDT           -0.002874