In [5]:
import pandas as pd

df = pd.read_pickle("/home/craz/crypto/crypto-trading/find_in_out_strategy/result/2025-10-01_2025-11-30/c2/stats_summary.pkl")

df.head(10)

,config,A,B,C,count,win_rate,avg_pnl,avg_holding,avg_win,avg_loss,profit_loss_ratio,stats_text
0,paras_0.01_0.01_0.001,0.01,0.01,0.0010,1372,0.383382,-0.000968,88.186589,0.013895,-0.010210,1.360942,Trade stats:\nCount: 1372\nWin Rate: 38.34%\nA...
1,paras_0.01_0.01_0.0013,0.01,0.01,0.0013,1372,0.389942,-0.000955,80.551749,0.013486,-0.010185,1.324111,Trade stats:\nCount: 1372\nWin Rate: 38.99%\nA...
2,paras_0.01_0.01_0.0016,0.01,0.01,0.0016,1372,0.387755,-0.001028,72.076531,0.013253,-0.010073,1.315704,Trade stats:\nCount: 1372\nWin Rate: 38.78%\nA...
3,paras_0.01_0.01_0.0019,0.01,0.01,0.0019,1372,0.389213,-0.001055,66.707726,0.013027,-0.010029,1.298952,Trade stats:\nCount: 1372\nWin Rate: 38.92%\nA...
4,paras_0.01_0.01_0.0022,0.01,0.01,0.0022,1372,0.387755,-0.001137,61.426385,0.012811,-0.009970,1.284902,Trade stats:\nCount: 1372\nWin Rate: 38.78%\nA...
5,paras_0.01_0.01_0.0025,0.01,0.01,0.0025,1372,0.386297,-0.001196,57.352770,0.012635,-0.009902,1.275921,Trade stats:\nCount: 1372\nWin Rate: 38.63%\nA...
6,paras_0.01_0.01_0.0028,0.01,0.01,0.0028,1372,0.388484,-0.001164,53.840379,0.012569,-0.009888,1.271098,Trade stats:\nCount: 1372\nWin Rate: 38.85%\nA...
7,paras_0.01_0.01_0.0031,0.01,0.01,0.0031,1372,0.392857,-0.001180,50.309038,0.012322,-0.009917,1.242524,Trade stats:\nCount: 1372\nWin Rate: 39.29%\nA...
8,paras_0.01_0.01_0.0034,0.01,0.01,0.0034,1372,0.394315,-0.001203,47.170554,0.012162,-0.009904,1.227996,Trade stats:\nCount: 1372\nWin Rate: 39.43%\nA...
9,paras_0.01_0.01_0.0037,0.01,0.01,0.0037,1372,0.397230,-0.001271,44.761662,0.011863,-0.009926,1.195174,Trade stats:\nCount: 1372\nWin Rate: 39.72%\nA...

In [7]:
df_ranked = df.sort_values("avg_pnl", ascending=False).reset_index(drop=True)
pd.set_option('display.max_rows', None)  
df_ranked.head(50)

,config,A,B,C,count,win_rate,avg_pnl,avg_holding,avg_win,avg_loss,profit_loss_ratio,stats_text
0,paras_0.07_0.031_0.001,0.070,0.031,0.0010,1372,0.508746,0.003566,750.700437,0.045892,-0.040267,1.139712,Trade stats:\nCount: 1372\nWin Rate: 50.87%\nA...
1,paras_0.065_0.031_0.001,0.065,0.031,0.0010,1372,0.502187,0.003303,725.623178,0.045335,-0.039098,1.159520,Trade stats:\nCount: 1372\nWin Rate: 50.22%\nA...
2,paras_0.055_0.031_0.001,0.055,0.031,0.0010,1372,0.490525,0.003259,672.596210,0.044122,-0.036084,1.222754,Trade stats:\nCount: 1372\nWin Rate: 49.05%\nA...
3,paras_0.07_0.034_0.001,0.070,0.034,0.0010,1372,0.494169,0.003162,775.021137,0.047776,-0.040424,1.181876,Trade stats:\nCount: 1372\nWin Rate: 49.42%\nA...
4,paras_0.07_0.028_0.001,0.070,0.028,0.0010,1372,0.521137,0.003131,706.000729,0.042096,-0.039274,1.071873,Trade stats:\nCount: 1372\nWin Rate: 52.11%\nA...
5,paras_0.07_0.037_0.001,0.070,0.037,0.0010,1372,0.486880,0.003109,797.225948,0.049936,-0.041323,1.208431,Trade stats:\nCount: 1372\nWin Rate: 48.69%\nA...
6,paras_0.06_0.031_0.001,0.060,0.031,0.0010,1372,0.495627,0.002995,697.259475,0.044126,-0.037424,1.179095,Trade stats:\nCount: 1372\nWin Rate: 49.56%\nA...
7,paras_0.065_0.037_0.001,0.065,0.037,0.0010,1372,0.479592,0.002958,770.435131,0.049525,-0.039957,1.239461,Trade stats:\nCount: 1372\nWin Rate: 47.96%\nA...
8,paras_0.065_0.028_0.001,0.065,0.028,0.0010,1372,0.516035,0.002931,684.075802,0.041604,-0.038304,1.086153,Trade stats:\nCount: 1372\nWin Rate: 51.60%\nA...
9,paras_0.065_0.034_0.001,0.065,0.034,0.0010,1372,0.486880,0.002929,749.254373,0.047317,-0.039188,1.207420,Trade stats:\nCount: 1372\nWin Rate: 48.69%\nA...
10,paras_0.06_0.028_0.0013,0.060,0.028,0.0013,1372,0.521137,0.002926,558.811224,0.038806,-0.036122,1.074304,Trade stats:\nCount: 1372\nWin Rate: 52.11%\nA...
11,paras_0.07_0.031_0.0013,0.070,0.031,0.0013,1372,0.524781,0.002922,635.225948,0.041865,-0.040084,1.044444,Trade stats:\nCount: 1372\nWin Rate: 52.48%\nA...
12,paras_0.055_0.028_0.001,0.055,0.028,0.0010,1372,0.505102,0.002910,634.338921,0.040665,-0.035624,1.141528,Trade stats:\nCount: 1372\nWin Rate: 50.51%\nA...
13,paras_0.06_0.031_0.0013,0.060,0.031,0.0013,1372,0.508017,0.002876,589.598397,0.041448,-0.036954,1.121612,Trade stats:\nCount: 1372\nWin Rate: 50.80%\nA...
14,paras_0.05_0.031_0.001,0.050,0.031,0.0010,1372,0.484694,0.002861,639.889942,0.042952,-0.034849,1.232509,Trade stats:\nCount: 1372\nWin Rate: 48.47%\nA...
15,paras_0.04_0.031_0.001,0.040,0.031,0.0010,1372,0.441691,0.002826,561.261662,0.043225,-0.029135,1.483648,Trade stats:\nCount: 1372\nWin Rate: 44.17%\nA...
16,paras_0.06_0.028_0.001,0.060,0.028,0.0010,1372,0.509475,0.002777,658.099854,0.040704,-0.036615,1.111680,Trade stats:\nCount: 1372\nWin Rate: 50.95%\nA...
17,paras_0.04_0.028_0.001,0.040,0.028,0.0010,1372,0.457726,0.002757,531.569971,0.040406,-0.029022,1.392259,Trade stats:\nCount: 1372\nWin Rate: 45.77%\nA...
18,paras_0.07_0.028_0.0013,0.070,0.028,0.0013,1372,0.536443,0.002746,600.043003,0.038970,-0.039172,0.994827,Trade stats:\nCount: 1372\nWin Rate: 53.64%\nA...
19,paras_0.06_0.028_0.0016,0.060,0.028,0.0016,1372,0.525510,0.002698,482.117347,0.037163,-0.035473,1.047651,Trade stats:\nCount: 1372\nWin Rate: 52.55%\nA...
20,paras_0.055_0.037_0.001,0.055,0.037,0.0010,1372,0.464286,0.002693,709.738338,0.048014,-0.036585,1.312392,Trade stats:\nCount: 1372\nWin Rate: 46.43%\nA...
21,paras_0.035_0.031_0.001,0.035,0.031,0.0010,1372,0.423469,0.002687,513.429300,0.042361,-0.026454,1.601288,Trade stats:\nCount: 1372\nWin Rate: 42.35%\nA...
22,paras_0.065_0.031_0.0013,0.065,0.031,0.0013,1372,0.516764,0.002664,612.037901,0.041483,-0.038848,1.067836,Trade stats:\nCount: 1372\nWin Rate: 51.68%\nA...
23,paras_0.055_0.034_0.001,0.055,0.034,0.0010,1372,0.472303,0.002664,691.529155,0.046054,-0.036172,1.273195,Trade stats:\nCount: 1372\nWin Rate: 47.23%\nA...
24,paras_0.055_0.025_0.001,0.055,0.025,0.0010,1372,0.521137,0.002663,593.230321,0.037278,-0.035008,1.064845,Trade stats:\nCount: 1372\nWin Rate: 52.11%\nA...
25,paras_0.045_0.031_0.001,0.045,0.031,0.0010,1372,0.460641,0.002660,600.082362,0.043494,-0.032215,1.350109,Trade stats:\nCount: 1372\nWin Rate: 46.06%\nA...
26,paras_0.07_0.025_0.001,0.070,0.025,0.0010,1372,0.532070,0.002658,658.283528,0.038419,-0.038006,1.010877,Trade stats:\nCount: 1372\nWin Rate: 53.21%\nA...
27,paras_0.07_0.037_0.0013,0.070,0.037,0.0013,1372,0.501458,0.002627,672.081633,0.045925,-0.040924,1.122211,Trade stats:\nCount: 1372\nWin Rate: 50.15%\nA...
28,paras_0.055_0.028_0.0013,0.055,0.028,0.0013,1372,0.506560,0.002616,534.140671,0.039005,-0.034741,1.122724,Trade stats:\nCount: 1372\nWin Rate: 50.66%\nA...
29,paras_0.06_0.025_0.0013,0.060,0.025,0.0013,1372,0.534257,0.002614,524.518222,0.035678,-0.035314,1.010297,Trade stats:\nCount: 1372\nWin Rate: 53.43%\nA...
30,paras_0.065_0.025_0.001,0.065,0.025,0.0010,1372,0.527697,0.002607,638.395044,0.038277,-0.037246,1.027657,Trade stats:\nCount: 1372\nWin Rate: 52.77%\nA...
31,paras_0.04_0.028_0.0013,0.040,0.028,0.0013,1372,0.460641,0.002588,450.165452,0.038852,-0.028384,1.368825,Trade stats:\nCount: 1372\nWin Rate: 46.06%\nA...
32,paras_0.065_0.028_0.0013,0.065,0.028,0.0013,1372,0.529883,0.002583,579.540087,0.038597,-0.038009,1.015464,Trade stats:\nCount: 1372\nWin Rate: 52.99%\nA...
33,paras_0.04_0.025_0.001,0.040,0.025,0.0010,1372,0.478134,0.002571,500.985423,0.036982,-0.028955,1.277199,Trade stats:\nCount: 1372\nWin Rate: 47.81%\nA...
34,paras_0.07_0.028_0.0019,0.070,0.028,0.0019,1372,0.537172,0.002570,460.470117,0.037036,-0.037433,0.989396,Trade stats:\nCount: 1372\nWin Rate: 53.72%\nA...
35,paras_0.055_0.031_0.0013,0.055,0.031,0.0013,1372,0.491254,0.002563,562.019679,0.041632,-0.035162,1.183981,Trade stats:\nCount: 1372\nWin Rate: 49.13%\nA...
36,paras_0.07_0.034_0.0013,0.070,0.034,0.0013,1372,0.509475,0.002562,654.194606,0.043664,-0.040128,1.088122,Trade stats:\nCount: 1372\nWin Rate: 50.95%\nA...
37,paras_0.05_0.028_0.001,0.050,0.028,0.0010,1372,0.500729,0.002556,604.413265,0.039498,-0.034493,1.145095,Trade stats:\nCount: 1372\nWin Rate: 50.07%\nA...
38,paras_0.035_0.028_0.001,0.035,0.028,0.0010,1372,0.439504,0.002553,484.857143,0.039548,-0.026456,1.494871,Trade stats:\nCount: 1372\nWin Rate: 43.95%\nA...
39,paras_0.045_0.028_0.001,0.045,0.028,0.0010,1372,0.477405,0.002538,568.506560,0.040338,-0.031993,1.260838,Trade stats:\nCount: 1372\nWin Rate: 47.74%\nA...
40,paras_0.04_0.031_0.0013,0.040,0.031,0.0013,1372,0.446064,0.002523,474.417638,0.041035,-0.028490,1.440336,Trade stats:\nCount: 1372\nWin Rate: 44.61%\nA...
41,paras_0.06_0.037_0.001,0.060,0.037,0.0010,1372,0.468659,0.002508,738.591837,0.048569,-0.038120,1.274115,Trade stats:\nCount: 1372\nWin Rate: 46.87%\nA...
42,paras_0.06_0.025_0.001,0.060,0.025,0.0010,1372,0.522595,0.002489,614.963557,0.037449,-0.035779,1.046668,Trade stats:\nCount: 1372\nWin Rate: 52.26%\nA...
43,paras_0.07_0.025_0.0013,0.070,0.025,0.0013,1372,0.545918,0.002475,562.091108,0.035994,-0.037824,0.951625,Trade stats:\nCount: 1372\nWin Rate: 54.59%\nA...
44,paras_0.06_0.031_0.0016,0.060,0.031,0.0016,1372,0.512391,0.002461,506.273324,0.039337,-0.036289,1.084006,Trade stats:\nCount: 1372\nWin Rate: 51.24%\nA...
45,paras_0.04_0.025_0.0013,0.040,0.025,0.0013,1372,0.481778,0.002453,426.921283,0.035678,-0.028437,1.254666,Trade stats:\nCount: 1372\nWin Rate: 48.18%\nA...
46,paras_0.07_0.031_0.0019,0.070,0.031,0.0019,1372,0.526239,0.002446,483.274781,0.039225,-0.038407,1.021293,Trade stats:\nCount: 1372\nWin Rate: 52.62%\nA...
47,paras_0.05_0.025_0.001,0.050,0.025,0.0010,1372,0.517493,0.002444,567.225219,0.036507,-0.034089,1.070934,Trade stats:\nCount: 1372\nWin Rate: 51.75%\nA...
48,paras_0.07_0.028_0.0016,0.070,0.028,0.0016,1372,0.534257,0.002436,517.968659,0.037669,-0.037981,0.991788,Trade stats:\nCount: 1372\nWin Rate: 53.43%\nA...
49,paras_0.06_0.025_0.0016,0.060,0.025,0.0016,1372,0.537901,0.002427,453.372449,0.034312,-0.034689,0.989138,Trade stats:\nCount: 1372\nWin Rate: 53.79%\nA...